service: pixel-machine-gun

provider:
  name: aws
  stage: beta
  runtime: nodejs6.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:${self:provider.region}:*:*"

custom:
  accountId: 649052894197
  webpackIncludeModules: false # disable auto including modules

plugins:
  - serverless-webpack
  - serverless-step-functions

resources:
  Resources:
    DeadPixelsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DeadPixels
        AttributeDefinitions:
          - AttributeName: hid
            AttributeType: N
        KeySchema:
          - AttributeName: hid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"

stepFunctions:
  stateMachines:
    pixelMachineGun:
      name: pixelMachineGun
      events:
        - http:
            path: pixel/fire
            method: POST
      definition:
        Comment: "Fire pixel in headless chrome"
        StartAt: Wait
        States:
          Wait:
            Type: Wait
            Seconds: 1
            Next: FirePixel
          FirePixel:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountId}:function:${self:service}-${self:provider.stage}-firePixel
            Retry:
            - ErrorEquals:
              - PixelFailsToFireError
              IntervalSeconds: 1
              MaxAttempts: 2
              BackoffRate: 2
            Catch:
            - ErrorEquals:
              - States.ALL
              Next: AddDeadPixel
            End: true
          AddDeadPixel:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountId}:function:${self:service}-${self:provider.stage}-addDeadPixel
            End: true

functions:
  firePixel:
    description: Fire pixel in headless chrome
    handler: handler.firePixel
    memorySize: 1024
    timeout: 30
    environment:
      CHROME_PATH: ./headless-chrome/headless_shell
  addDeadPixel:
    description: Add dead pixel to DynamoDB table
    handler: handler.addDeadPixel
    timeout: 5
  postToSlack:
    description: Post table changes to slack
    handler: handler.postToSlack
    timeout: 5
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - DeadPixelsTable
              - StreamArn
