service: headless-chrome

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:us-east-1:*:*"
  environment:
    CHROME_PATH: ./headless-chrome/headless_shell

custom:
  webpackIncludeModules: false # disable auto including modules

plugins:
  - serverless-webpack

resources:
  Resources:
    DeadPixelsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DeadPixels
        AttributeDefinitions:
          - AttributeName: hid
            AttributeType: N
        KeySchema:
          - AttributeName: hid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"

functions:
  firePixel:
    description: Fire pixel in headless chrome
    handler: handler.firePixel
    memorySize: 1024
    timeout: 10
  addDeadPixel:
    description: Add dead pixel to DynamoDB table
    handler: handler.addDeadPixel
    timeout: 5
  postToSlack:
    description: Post table changes to slack
    handler: handler.postToSlack
    timeout: 5
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - DeadPixelsTable
              - StreamArn
