service: headless-chrome

provider:
  name: aws
  role: arn:aws:iam::649052894197:role/lambda_fire_pixel
  runtime: nodejs6.10
  region: us-east-1
  environment:
    CHROME_PATH: ./headless-chrome/headless_shell

custom:
  webpackIncludeModules: false # disable auto including modules

plugins:
  - serverless-webpack

functions:
  fire-pixel:
    description: Fire pixel in headless chrome
    memorySize: 1024
    timeout: 30
    handler: handler.run
